<script lang="ts">
	import { resolve } from '$app/paths';
	import CubeDiagram from '$components/cube/CubeDiagram.svelte';
	import AlgCase from '$components/cube/AlgCase.svelte';
	import Chip from '$components/ui/Chip.svelte';
	import Segmented from '$components/ui/Segmented.svelte';
	import AlgString from '$components/ui/AlgString.svelte';
	import { pageTitle } from '$lib/brand';
	import { ALG_SETS, casesOfSet, filterCases, RESOLVED_CASES } from '$data/algorithms';
	import { SKILL_LABELS, SKILL_TIERS, type AlgSetId, type SkillTier } from '$data/types';
	import { progress } from '$state/progress.svelte';
	import { PUZZLE_LABELS, settings } from '$state/settings.svelte';

	let query = $state('');
	let tierFilter = $state<SkillTier | 'all'>('all');
	let setFilter = $state<AlgSetId | 'all'>('all');

	// The library holds sets for every puzzle, but showing a reader 3×3 OLL while
	// they are on a 2×2 would be a lie of omission. Sets carry their puzzle, and
	// anything authored before the site had modes is a 3×3.
	const order = $derived(settings.current.puzzle);
	const sets = $derived(ALG_SETS.filter((s) => (s.puzzle ?? 3) === order));
	const setIds = $derived(new Set(sets.map((s) => s.id)));

	const searching = $derived(
		query.trim().length > 0 || tierFilter !== 'all' || setFilter !== 'all'
	);

	const results = $derived(
		filterCases({
			query: query.trim() || undefined,
			tiers: tierFilter === 'all' ? undefined : [tierFilter],
			sets: setFilter === 'all' ? undefined : [setFilter]
		}).filter((c) => setIds.has(c.set))
	);

	const counts = $derived(
		Object.fromEntries(sets.map((s) => [s.id, casesOfSet(s.id).length])) as Record<AlgSetId, number>
	);

	const knownCounts = $derived(
		Object.fromEntries(
			sets.map((s) => [
				s.id,
				casesOfSet(s.id).filter((c) => progress.confidence(c.id) === 'solid').length
			])
		) as Record<AlgSetId, number>
	);

	/** A representative case per set, for the card's thumbnail. */
	function thumbnail(id: AlgSetId) {
		return casesOfSet(id)[0];
	}

	const total = $derived(RESOLVED_CASES.filter((c) => setIds.has(c.set)).length);
	const algs = $derived(
		RESOLVED_CASES.filter((c) => setIds.has(c.set)).reduce((n, c) => n + c.algs.length, 0)
	);

	// A set the reader had filtered to can vanish when the puzzle changes.
	$effect(() => {
		if (setFilter !== 'all' && !setIds.has(setFilter)) setFilter = 'all';
	});
</script>

<svelte:head>
	<title>{pageTitle('algorithms')}</title>
	<meta
		name="description"
		content="Every Rubik's Cube algorithm worth knowing, searchable, with diagrams generated from the moves themselves."
	/>
</svelte:head>

<div class="page page--wide">
	<header class="head">
		<p class="eyebrow">Algorithms · {PUZZLE_LABELS[order]}</p>
		<h1>{total} cases. {algs} algorithms. All of them checked.</h1>
		<p class="lede">
			Everything below is for the {PUZZLE_LABELS[order]} — switch puzzles in the header and the library
			switches with you. Search it all at once, or work through a set at your own pace. Every diagram
			here is generated by running the algorithm backwards on a solved puzzle, so the picture and the
			moves can never disagree.
		</p>
	</header>

	<div class="controls">
		<label class="search">
			<span class="visually-hidden">Search every algorithm</span>
			<input
				type="search"
				placeholder="Search 'T perm', 'sledgehammer', 'R U R'', 'dot'…"
				bind:value={query}
				spellcheck="false"
			/>
		</label>

		<Segmented
			label="Filter by level"
			size="sm"
			value={tierFilter}
			onchange={(v) => (tierFilter = v)}
			options={[
				{ value: 'all' as const, label: 'All levels' },
				...SKILL_TIERS.map((t) => ({ value: t, label: SKILL_LABELS[t] }))
			]}
		/>
	</div>

	{#if searching}
		<section class="results">
			<div class="results__bar">
				<h2>
					{results.length}
					{results.length === 1 ? 'case' : 'cases'}
					{#if setFilter !== 'all'}in {sets.find((s) => s.id === setFilter)?.shortName}{/if}
				</h2>
				<button
					class="clear"
					type="button"
					onclick={() => {
						query = '';
						tierFilter = 'all';
						setFilter = 'all';
					}}
				>
					Clear
				</button>
			</div>

			{#if results.length === 0}
				<p class="empty">
					Nothing matches that. Search accepts case names, algorithm text, trigger names and tags —
					try a shorter query.
				</p>
			{:else}
				<div class="cases">
					{#each results.slice(0, 60) as entry (entry.id)}
						<AlgCase {entry} />
					{/each}
				</div>
				{#if results.length > 60}
					<p class="more">
						Showing the first 60 of {results.length}. Narrow the search, or open a set below to see
						everything in it.
					</p>
				{/if}
			{/if}
		</section>
	{/if}

	<section class="sets" aria-label="Algorithm sets">
		<h2 class="sets__heading">The sets</h2>
		<div class="sets__grid">
			{#each sets as set (set.id)}
				{@const sample = thumbnail(set.id)}
				<a class="set" href={resolve('/algorithms/[set]', { set: set.id })}>
					<div class="set__thumb">
						{#if sample}
							<CubeDiagram
								facelets={sample.caseState}
								{order}
								view={set.view}
								size={96}
								label="A case from {set.name}"
							/>
						{/if}
					</div>
					<div class="set__body">
						<h3 class="set__name">{set.shortName}</h3>
						<p class="set__summary">{set.summary}</p>
						<div class="set__meta">
							<Chip tone="section">{counts[set.id]} cases</Chip>
							<Chip>{SKILL_LABELS[set.tier]}</Chip>
							{#if knownCounts[set.id] > 0}
								<Chip tone="positive">{knownCounts[set.id]} known</Chip>
							{/if}
						</div>
						{#if sample}
							<div class="set__sample scroll-x">
								<AlgString alg={sample.algs[0].moves} size="sm" wrap={false} />
							</div>
						{/if}
					</div>
				</a>
			{/each}
		</div>
	</section>
</div>

<style>
	.head {
		max-width: var(--measure);
		margin-block-end: var(--space-5);
	}

	.head h1 {
		margin-block: var(--space-2) var(--space-4);
	}

	.lede {
		color: var(--text-muted);
		font-size: var(--step-1);
		line-height: var(--leading-snug);
	}

	.controls {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: var(--space-3);
		position: sticky;
		top: var(--header-height);
		z-index: 20;
		padding-block: var(--space-3);
		background: color-mix(in oklab, var(--bg) 92%, transparent);
		backdrop-filter: blur(10px);
	}

	.search {
		flex: 1 1 20rem;
	}

	.search input {
		width: 100%;
		padding: 0.65em 0.9em;
		background: var(--surface-1);
		border: var(--border-strong);
		border-radius: var(--radius-2);
		font-size: var(--step-0);
	}

	.search input:focus-visible {
		border-color: var(--accent);
	}

	.results {
		margin-block-end: var(--space-7);
	}

	.results__bar {
		display: flex;
		align-items: baseline;
		justify-content: space-between;
		gap: var(--space-3);
		margin-block-end: var(--space-4);
	}

	.results__bar h2 {
		font-size: var(--step-1);
	}

	.clear {
		color: var(--text-muted);
		font-size: var(--step--1);
		text-decoration: underline;
		text-underline-offset: 3px;
	}

	.clear:hover {
		color: var(--text);
	}

	.cases {
		display: grid;
		gap: var(--space-3);
	}

	.empty,
	.more {
		padding: var(--space-5);
		color: var(--text-muted);
		font-size: var(--step--1);
		text-align: center;
	}

	.sets__heading {
		margin-block: var(--space-6) var(--space-4);
		padding-block-end: var(--space-2);
		border-bottom: 2px solid var(--section-edge);
		font-size: var(--step-2);
	}

	.sets__grid {
		display: grid;
		gap: var(--space-4);
		grid-template-columns: repeat(auto-fill, minmax(20rem, 1fr));
	}

	.set {
		display: grid;
		grid-template-columns: auto minmax(0, 1fr);
		gap: var(--space-4);
		padding: var(--space-4);
		background: var(--surface-1);
		border: var(--border);
		border-radius: var(--radius-3);
		text-decoration: none;
		color: inherit;
		transition:
			border-color var(--dur-fast) var(--ease-out),
			transform var(--dur-fast) var(--ease-out);
	}

	.set:hover {
		border-color: var(--section);
		transform: translateY(-2px);
	}

	.set__thumb {
		display: grid;
		place-items: start center;
	}

	.set__body {
		display: grid;
		gap: var(--space-2);
		align-content: start;
		min-width: 0;
	}

	.set__name {
		font-size: var(--step-1);
		font-weight: 640;
	}

	.set__summary {
		color: var(--text-muted);
		font-size: var(--step--1);
		line-height: var(--leading-snug);
	}

	.set__meta {
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-2);
	}

	.set__sample {
		padding-block-start: var(--space-2);
		border-top: var(--border);
	}
</style>
