<!--
	The notation reference.

	Every turn on this page is shown as a picture of what it does to a solved cube,
	generated by running the move rather than drawn by hand, so the caption and the
	diagram cannot disagree. Each card can be flipped back to the solved cube it
	started from, because "what changed?" is the only question a notation diagram
	is really answering.
-->
<script lang="ts">
	import { resolve } from '$app/paths';
	import CubeDiagram from '$components/cube/CubeDiagram.svelte';
	import InteractiveCube from '$components/lesson/InteractiveCube.svelte';
	import AlgString from '$components/ui/AlgString.svelte';
	import Prose from '$components/lesson/Prose.svelte';
	import Chip from '$components/ui/Chip.svelte';
	import { solvedFacelets, stateFromAlg } from '$cube/facelets';
	import { pageTitle } from '$lib/brand';

	interface MoveNote {
		/** The move, in canonical notation. */
		move: string;
		/** What it is called in words. */
		title: string;
		/** What it does, and what people get wrong about it. */
		blurb: string;
	}

	const SOLVED = solvedFacelets();

	const FACE_TURNS: readonly MoveNote[] = [
		{
			move: 'U',
			title: 'Up',
			blurb: 'The top layer, clockwise seen from above. The front row travels round to the left.'
		},
		{
			move: 'D',
			title: 'Down',
			blurb:
				'The bottom layer, clockwise seen from **below**. From where you are sitting it looks anticlockwise, and the front row travels round to the right.'
		},
		{
			move: 'R',
			title: 'Right',
			blurb: 'The right-hand layer, clockwise seen from the right. The front column goes upwards.'
		},
		{
			move: 'L',
			title: 'Left',
			blurb:
				'The left-hand layer, clockwise seen from the **left** — so it looks anticlockwise from the front, and the front column goes downwards.'
		},
		{
			move: 'F',
			title: 'Front',
			blurb:
				'The face nearest you, clockwise as you look at it. The top row goes round to the right.'
		},
		{
			move: 'B',
			title: 'Back',
			blurb:
				'The far face, clockwise seen from **behind** the cube. From the front it reads anticlockwise: the top row goes round to the left.'
		}
	];

	const MODIFIERS: readonly MoveNote[] = [
		{ move: 'R', title: 'Plain letter', blurb: 'A quarter turn clockwise, seen from that face.' },
		{
			move: "R'",
			title: 'Prime',
			blurb:
				'The same quarter turn the other way round. `R\'` undoes `R`, and the two together leave the cube untouched. Said aloud as "R prime".'
		},
		{
			move: 'R2',
			title: 'Half turn',
			blurb:
				"Two quarter turns. It arrives in the same place whichever way you go, so it never takes a prime — nobody writes `R2'`."
		}
	];

	const WIDE_TURNS: readonly MoveNote[] = [
		{
			move: 'Rw',
			title: 'Wide right',
			blurb:
				"The right face and the slice behind it, turning together the way `R` turns. Also written `r`. Equal to `R M'`."
		},
		{
			move: 'Uw',
			title: 'Wide up',
			blurb:
				"The top face and the slice below it, turning the way `U` turns. Also written `u`. Equal to `U E'`."
		},
		{
			move: 'Fw',
			title: 'Wide front',
			blurb:
				'The front face and the slice behind it, turning the way `F` turns. Also written `f`. Equal to `F S`.'
		}
	];

	const SLICE_TURNS: readonly MoveNote[] = [
		{
			move: 'M',
			title: 'Middle',
			blurb:
				'The slice between L and R, following **L**. The top of the middle column comes towards you and down the front.'
		},
		{
			move: 'E',
			title: 'Equator',
			blurb:
				'The slice between U and D, following **D**. The front of the belt goes round to the right.'
		},
		{
			move: 'S',
			title: 'Standing',
			blurb:
				'The slice between F and B, following **F**. The top of the slice goes round to the right.'
		}
	];

	const ROTATIONS: readonly MoveNote[] = [
		{
			move: 'x',
			title: 'Roll forward',
			blurb:
				'The whole cube in the direction of `R`. The front face rolls up to the top — this is how you look at the bottom layer without losing your place.'
		},
		{
			move: 'y',
			title: 'Spin',
			blurb:
				'The whole cube in the direction of `U`. The right face comes round to the front. This is the rotation you make between F2L pairs.'
		},
		{
			move: 'z',
			title: 'Tip sideways',
			blurb:
				'The whole cube in the direction of `F`. The left face comes up to the top, and everything you knew about which hand does what changes with it.'
		}
	];

	const CONTENTS: readonly { id: string; label: string }[] = [
		{ id: 'faces', label: 'Face turns' },
		{ id: 'modifiers', label: "' and 2" },
		{ id: 'wide', label: 'Wide turns' },
		{ id: 'slices', label: 'Slices' },
		{ id: 'rotations', label: 'Rotations' },
		{ id: 'reading', label: 'Reading an algorithm' },
		{ id: 'try', label: 'Try it' },
		{ id: 'summary', label: 'The whole thing' }
	];

	const KEYPAD: readonly string[] = [
		'U',
		"U'",
		'R',
		"R'",
		'F',
		"F'",
		'D',
		"D'",
		'L',
		"L'",
		'B',
		"B'",
		'M',
		"M'",
		'E',
		"E'",
		'S',
		"S'",
		'Rw',
		"Rw'",
		'Uw',
		"Uw'",
		'Fw',
		"Fw'",
		'x',
		"x'",
		'y',
		"y'",
		'z',
		"z'"
	];

	/** Which cards are currently showing the solved cube instead of the result. */
	let before = $state<Record<string, boolean>>({});

	/** Cards are keyed by section as well as move, since `R` appears twice. */
	const keyFor = (section: string, move: string) => `${section}:${move}`;
</script>

<svelte:head>
	<title>{pageTitle('notation')}</title>
	<meta
		name="description"
		content="What every letter, prime mark and lowercase turn means, with a picture of what each one does to a solved cube."
	/>
</svelte:head>

{#snippet moveCard(section: string, m: MoveNote)}
	{@const key = keyFor(section, m.move)}
	{@const showing = before[key] === true}
	<div class="card">
		<div class="card__head">
			<AlgString alg={m.move} size="lg" />
			<span class="card__title">{m.title}</span>
		</div>
		<button
			type="button"
			class="card__view"
			onclick={() => (before[key] = !showing)}
			aria-label={showing
				? `Show the cube after ${m.move}`
				: `Show the solved cube ${m.move} started from`}
		>
			<CubeDiagram
				facelets={showing ? SOLVED : stateFromAlg(m.move)}
				view="full"
				size={124}
				label={showing ? 'A solved cube' : `A solved cube after ${m.move}`}
			/>
			<span class="card__state">
				{showing ? 'solved — tap to turn' : `after ${m.move} — tap to compare`}
			</span>
		</button>
		<Prose text={m.blurb} class="card__blurb" />
	</div>
{/snippet}

<div class="page">
	<header class="head">
		<p class="eyebrow">Notation</p>
		<h1>Every letter, and what it does to the cube.</h1>
		<p class="lede">
			The notation is small: six faces, two modifiers, and a handful of turns that move more than
			one layer. Learn it once and every algorithm on this site — and in every guide you will ever
			read — becomes readable. Each picture below is a solved cube after that single turn, and you
			can tap any of them to flip back to the solved cube and see exactly what moved.
		</p>
	</header>

	<nav class="contents" aria-label="On this page">
		{#each CONTENTS as item (item.id)}
			<a class="contents__link" href="#{item.id}">{item.label}</a>
		{/each}
	</nav>

	<section class="section" aria-labelledby="positions">
		<h2 class="section__heading" id="positions">The letters name positions, not colours</h2>
		<div class="intro">
			<div class="intro__text">
				<p>
					A letter names whichever face is pointing that way <em>at this moment</em>. Turn the cube
					in your hands and <code>R</code> becomes a different face entirely. That is why an algorithm
					works whatever colour you happen to be looking at, and why so many instructions begin by telling
					you how to hold the cube rather than what to turn.
				</p>
				<p>
					The pictures on this page start from a solved cube drawn the usual way for diagrams: white
					up, green in front, red on the right. When you are solving on this site, white goes on the
					<strong>bottom</strong> and yellow finishes on top — so during a solve,
					<code>U</code> is the yellow face. The letters do not change. Only what sits under them does.
				</p>
			</div>
			<figure class="intro__figure">
				<CubeDiagram
					facelets={SOLVED}
					view="full"
					size={150}
					label="A solved cube with white on top, green in front and red on the right"
				/>
				<figcaption>The starting cube for every picture below.</figcaption>
			</figure>
		</div>

		<aside class="note note--tip">
			<p class="note__title">The one that catches everyone</p>
			<p class="note__text">
				Direction is judged <strong>from outside the face being turned</strong>, never from where
				you happen to be sitting. <code>L</code> looks anticlockwise from the front because you are
				seeing the back of the left face. The same goes for <code>D</code> and <code>B</code>. The
				fix is to picture yourself standing in front of the face you are about to turn, and turn it
				clockwise from there.
			</p>
		</aside>
	</section>

	<section class="section" aria-labelledby="faces">
		<h2 class="section__heading" id="faces">The six face turns</h2>
		<p class="section__lede">
			One letter per face. Each turns a single layer — the nine pieces on that side of the cube —
			and leaves the other eighteen where they were.
		</p>
		<div class="cards">
			{#each FACE_TURNS as m (m.move)}
				{@render moveCard('face', m)}
			{/each}
		</div>
	</section>

	<section class="section" aria-labelledby="modifiers">
		<h2 class="section__heading" id="modifiers">Two modifiers</h2>
		<p class="section__lede">
			Every letter comes in three forms, and they apply to slices, wide turns and rotations exactly
			as they do to faces.
		</p>
		<div class="cards cards--three">
			{#each MODIFIERS as m (m.move)}
				{@render moveCard('modifier', m)}
			{/each}
		</div>
		<aside class="note note--insight">
			<p class="note__title">Why the prime is worth having</p>
			<p class="note__text">
				Four quarter turns of the same face bring it back to where it started, so <code>R R R</code>
				and <code>R'</code> do the same job. The prime is there to save you two turns and your wrist.
				It is also how you undo an algorithm: reverse the order of the moves and prime every one of them.
			</p>
		</aside>
	</section>

	<section class="section" aria-labelledby="wide">
		<h2 class="section__heading" id="wide">Wide turns: two layers at once</h2>
		<p class="section__lede">
			A wide turn takes a face <em>and the slice behind it</em> — two of the three layers, going the
			way the outer face goes. Written with a <code>w</code> as
			<code>Rw</code>, or as a lowercase <code>r</code>. The two spellings mean the same thing, and
			you can choose which one this site shows you in the appearance menu.
		</p>
		<div class="cards cards--three">
			{#each WIDE_TURNS as m (m.move)}
				{@render moveCard('wide', m)}
			{/each}
		</div>
		<p class="section__note">
			<code>Lw</code>, <code>Dw</code> and <code>Bw</code> exist too, and behave the same way: the face
			plus the slice next to it, in the direction of the face.
		</p>
		<aside class="note note--warning">
			<p class="note__title">A wide turn is not a rotation</p>
			<p class="note__text">
				<code>Rw</code> leaves the left-hand layer exactly where it was, so it scrambles the cube as
				well as tilting it. <code>x</code> turns all three layers and scrambles nothing. The other
				thing to watch is that a wide turn carries centres with it, so after one, <code>U</code> and
				<code>F</code> point at different colours than they did — which is why algorithms built from wide
				turns usually end with a rotation to put your hands back.
			</p>
		</aside>
	</section>

	<section class="section" aria-labelledby="slices">
		<h2 class="section__heading" id="slices">Slice turns: the middle layer alone</h2>
		<p class="section__lede">
			A slice turn moves a middle layer and leaves both outer faces standing. There are three, one
			per axis. The only genuinely awkward thing about them is which way round each one goes — and
			that is the thing people forget, so here it is as a table before anything else.
		</p>

		<div class="scroll-x">
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Slice</th>
						<th scope="col">The layer</th>
						<th scope="col">Follows</th>
						<th scope="col">Name</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><AlgString alg="M" size="sm" /></td>
						<td>Between L and R</td>
						<td><AlgString alg="L" size="sm" /></td>
						<td>Middle</td>
					</tr>
					<tr>
						<td><AlgString alg="E" size="sm" /></td>
						<td>Between U and D</td>
						<td><AlgString alg="D" size="sm" /></td>
						<td>Equator</td>
					</tr>
					<tr>
						<td><AlgString alg="S" size="sm" /></td>
						<td>Between F and B</td>
						<td><AlgString alg="F" size="sm" /></td>
						<td>Standing</td>
					</tr>
				</tbody>
			</table>
		</div>

		<div class="cards cards--three">
			{#each SLICE_TURNS as m (m.move)}
				{@render moveCard('slice', m)}
			{/each}
		</div>

		<aside class="note note--insight">
			<p class="note__title">There is no reason M follows L</p>
			<p class="note__text">
				It is a convention, fixed decades ago, and everyone has agreed to live with it rather than
				argue. The consequence worth carrying around is that plain <code>M</code> brings the middle
				column down the front and <code>M'</code> takes it up — so check the mark before running an algorithm
				from memory, because the two leave the cube in very different places.
			</p>
		</aside>
		<p class="section__note">
			Slices carry centres, so an algorithm full of <code>M</code> turns can leave a cube that looks solved
			but sits rotated. It is also why the H and Z permutations are written with them: rocking the middle
			slice back and forth swaps opposite edges without touching a single corner.
		</p>
	</section>

	<section class="section" aria-labelledby="rotations">
		<h2 class="section__heading" id="rotations">Cube rotations: turning yourself, not the cube</h2>
		<p class="section__lede">
			<code>x</code>, <code>y</code> and <code>z</code> turn the whole cube in your hands. No piece moves
			relative to any other, so nothing is solved and nothing is broken — but every letter that follows
			now means a different face, and that is the point of doing one.
		</p>
		<div class="cards cards--three">
			{#each ROTATIONS as m (m.move)}
				{@render moveCard('rotation', m)}
			{/each}
		</div>
		<p class="section__note">
			A rotation is the three parallel layers turning together, which is why <code>x</code> is
			<code>R M' L'</code>, <code>y</code> is <code>U E' D'</code> and <code>z</code> is
			<code>F S B'</code>. Algorithms on this site print rotations in a lighter italic style, so you
			can see at a glance where one expects you to move your hands rather than the cube.
		</p>
	</section>

	<section class="section" aria-labelledby="reading">
		<h2 class="section__heading" id="reading">Reading an algorithm</h2>
		<p class="section__lede">
			Everything on the site is written in the notation above. Seven rules cover all of it.
		</p>
		<ol class="rules">
			<li>
				Read left to right, one move at a time. Nothing happens at the same time as anything else.
			</li>
			<li>
				A prime is the same turn the other way. <code>R'</code> undoes <code>R</code>; a whole
				algorithm is undone by reversing it and priming every move.
			</li>
			<li>A <code>2</code> is half a turn, and never carries a prime.</li>
			<li>Direction is judged from outside the face being turned.</li>
			<li>
				<code>M</code> follows <code>L</code>, <code>E</code> follows <code>D</code>,
				<code>S</code> follows <code>F</code>.
			</li>
			<li>
				Lowercase and <code>w</code> mean the same wide turn: <code>r</code> is <code>Rw</code>, two
				layers deep.
			</li>
			<li>
				A rotation changes what every letter after it means. A wide turn changes it for the pieces
				it carried.
			</li>
		</ol>

		<div class="examples">
			<figure class="example">
				<div class="scroll-x"><AlgString alg="R U R' U'" size="md" count /></div>
				<figcaption>
					Four moves, one motion: right up, right back, up back. Most people learn this before they
					learn anything else, and six repetitions of it return the cube to solved.
				</figcaption>
			</figure>
			<figure class="example">
				<div class="scroll-x">
					<AlgString alg="R U R' U' R' F R2 U' R' U' R U R' F'" size="md" count />
				</div>
				<figcaption>
					The T permutation. Fourteen letters, but only four things your hands do — learn it as
					<code>R U R' U'</code>, then <code>R' F R2 U'</code>, then <code>R' U' R U</code>, then
					<code>R' F'</code>.
				</figcaption>
			</figure>
		</div>

		<aside class="note note--tip">
			<p class="note__title">Chunk it, do not spell it</p>
			<p class="note__text">
				An algorithm learnt as fourteen separate letters has to be recited. The same algorithm
				learnt as four triggers is something your hands already know how to do. The
				<a href={resolve('/glossary/')}>glossary</a> has the named ones — sexy move, sledgehammer,
				sune — and the
				<a href={resolve('/algorithms/')}>algorithm library</a> marks which triggers appear in each case.
			</p>
		</aside>
	</section>

	<section class="section" aria-labelledby="try">
		<h2 class="section__heading" id="try">Try it</h2>
		<p class="section__lede">
			Faces, slices, wide turns and rotations, all on one keypad. Drag the cube to look round the
			back of it.
		</p>
		<figure class="playground">
			<InteractiveCube
				initial={SOLVED}
				keys={KEYPAD}
				size={240}
				label="A solved cube you can turn with any move in the notation"
			/>
			<figcaption>
				A good first exercise: run <code>M</code> four times and watch the middle column go all the
				way round. A better second one: run <code>Rw</code> and then <code>x'</code>, and see what
				is left over.
			</figcaption>
		</figure>
	</section>

	<section class="section" aria-labelledby="summary">
		<h2 class="section__heading" id="summary">The whole thing on one screen</h2>
		<div class="scroll-x">
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Symbol</th>
						<th scope="col">Turns</th>
						<th scope="col">Which way</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><AlgString alg="U D R L F B" size="sm" /></td>
						<td>One face, one layer deep</td>
						<td>Clockwise, seen from outside that face</td>
					</tr>
					<tr>
						<td><AlgString alg="R'" size="sm" /></td>
						<td>The same layer</td>
						<td>Anticlockwise — the prime reverses any move</td>
					</tr>
					<tr>
						<td><AlgString alg="R2" size="sm" /></td>
						<td>The same layer</td>
						<td>Half a turn; direction does not matter</td>
					</tr>
					<tr>
						<td><AlgString alg="Rw Uw Fw" size="sm" /></td>
						<td>A face plus the slice behind it</td>
						<td>The way the outer face goes. Also written <code>r u f</code></td>
					</tr>
					<tr>
						<td><AlgString alg="M" size="sm" /></td>
						<td>The slice between L and R</td>
						<td>The way <code>L</code> goes</td>
					</tr>
					<tr>
						<td><AlgString alg="E" size="sm" /></td>
						<td>The slice between U and D</td>
						<td>The way <code>D</code> goes</td>
					</tr>
					<tr>
						<td><AlgString alg="S" size="sm" /></td>
						<td>The slice between F and B</td>
						<td>The way <code>F</code> goes</td>
					</tr>
					<tr>
						<td><AlgString alg="x" size="sm" /></td>
						<td>The whole cube</td>
						<td>The way <code>R</code> goes</td>
					</tr>
					<tr>
						<td><AlgString alg="y" size="sm" /></td>
						<td>The whole cube</td>
						<td>The way <code>U</code> goes</td>
					</tr>
					<tr>
						<td><AlgString alg="z" size="sm" /></td>
						<td>The whole cube</td>
						<td>The way <code>F</code> goes</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="chips">
			<Chip tone="section">18 face turns</Chip>
			<Chip>9 slice turns</Chip>
			<Chip>9 rotations</Chip>
			<Chip>Every algorithm on the site, in these letters</Chip>
		</div>
	</section>

	<nav class="jumps" aria-label="Where to next">
		<a class="jump" href={resolve('/learn/')}>
			<span class="jump__label">Learn to solve</span>
			<span class="jump__blurb">
				The beginner track starts from what a cube is made of and ends with a solved one.
			</span>
			<span class="jump__go" aria-hidden="true">→</span>
		</a>
		<a class="jump" href={resolve('/glossary/')}>
			<span class="jump__label">Glossary</span>
			<span class="jump__blurb">
				Sune, sledgehammer, lookahead, ao5 — sixty terms, defined plainly.
			</span>
			<span class="jump__go" aria-hidden="true">→</span>
		</a>
		<a class="jump" href={resolve('/algorithms/')}>
			<span class="jump__label">Algorithms</span>
			<span class="jump__blurb">
				Every case worth knowing, written in exactly the notation above.
			</span>
			<span class="jump__go" aria-hidden="true">→</span>
		</a>
	</nav>
</div>

<style>
	.head {
		max-width: var(--measure);
	}

	.head h1 {
		margin-block: var(--space-2) var(--space-4);
	}

	.lede {
		color: var(--text-muted);
		font-size: var(--step-1);
		line-height: var(--leading-snug);
	}

	.contents {
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-2);
		margin-block-start: var(--space-6);
		padding-block: var(--space-3);
		border-block: var(--border);
	}

	.contents__link {
		padding: 0.3em 0.7em;
		border: 1px solid var(--hairline);
		border-radius: var(--radius-pill);
		color: var(--text-muted);
		font-size: var(--step--1);
		text-decoration: none;
	}

	.contents__link:hover {
		border-color: var(--section);
		color: var(--text);
	}

	.section {
		margin-block-start: var(--space-7);
	}

	.section__heading {
		margin-block-end: var(--space-4);
		padding-block-end: var(--space-2);
		border-bottom: 2px solid var(--section-edge);
		font-size: var(--step-2);
		scroll-margin-block-start: calc(var(--header-height) + var(--space-4));
	}

	.section__lede,
	.section__note {
		max-width: var(--measure);
		margin-block-end: var(--space-4);
		color: var(--text-muted);
		line-height: var(--leading-loose);
	}

	.section__note {
		margin-block-start: var(--space-4);
		font-size: var(--step--1);
	}

	.intro {
		display: grid;
		gap: var(--space-5);
		grid-template-columns: minmax(0, 1fr);
		align-items: start;
		margin-block-end: var(--space-5);
	}

	@media (min-width: 48rem) {
		.intro {
			grid-template-columns: minmax(0, 1fr) auto;
		}
	}

	.intro__text {
		display: grid;
		gap: var(--space-4);
		max-width: var(--measure);
		line-height: var(--leading-loose);
	}

	.intro__figure {
		display: grid;
		justify-items: center;
		gap: var(--space-3);
		margin: 0;
		padding: var(--space-4);
		background: var(--surface-1);
		border: var(--border);
		border-radius: var(--radius-3);
	}

	figcaption {
		max-width: 22rem;
		color: var(--text-muted);
		font-size: var(--step--1);
		line-height: var(--leading-snug);
		text-align: center;
	}

	.cards {
		display: grid;
		gap: var(--space-4);
		grid-template-columns: repeat(auto-fill, minmax(15rem, 1fr));
	}

	.cards--three {
		grid-template-columns: repeat(auto-fill, minmax(17rem, 1fr));
	}

	.card {
		display: grid;
		gap: var(--space-3);
		align-content: start;
		padding: var(--space-4);
		background: var(--surface-1);
		border: var(--border);
		border-radius: var(--radius-3);
	}

	.card__head {
		display: flex;
		flex-wrap: wrap;
		align-items: baseline;
		gap: var(--space-3);
	}

	.card__title {
		color: var(--text-faint);
		font-size: var(--step--2);
		font-weight: 700;
		letter-spacing: var(--tracking-caps);
		text-transform: uppercase;
	}

	.card__view {
		display: grid;
		justify-items: center;
		gap: var(--space-2);
		padding: var(--space-3);
		background: var(--surface-2);
		border: 1px solid transparent;
		border-radius: var(--radius-2);
	}

	.card__view:hover {
		border-color: var(--section);
	}

	.card__state {
		color: var(--text-faint);
		font-family: var(--font-mono);
		font-size: var(--step--2);
	}

	.card :global(.card__blurb) {
		color: var(--text-muted);
		font-size: var(--step--1);
		line-height: var(--leading-normal);
	}

	.note {
		display: grid;
		gap: var(--space-2);
		max-width: var(--measure);
		margin-block-start: var(--space-5);
		padding: var(--space-4);
		border-inline-start: 3px solid var(--accent);
		border-radius: var(--radius-2);
		background: var(--surface-2);
	}

	.note--tip {
		border-inline-start-color: var(--positive);
	}
	.note--warning {
		border-inline-start-color: var(--caution);
	}
	.note--insight {
		border-inline-start-color: var(--accent);
	}

	.note__title {
		color: var(--text-faint);
		font-size: var(--step--2);
		font-weight: 700;
		letter-spacing: var(--tracking-caps);
		text-transform: uppercase;
	}

	.note__text {
		color: var(--text-muted);
		font-size: var(--step--1);
		line-height: var(--leading-normal);
	}

	.table {
		width: 100%;
		border-collapse: collapse;
		margin-block-end: var(--space-5);
		font-size: var(--step--1);
	}

	.table th,
	.table td {
		padding: var(--space-2) var(--space-3);
		border-bottom: var(--border);
		text-align: start;
		vertical-align: middle;
	}

	.table th {
		color: var(--text-faint);
		font-size: var(--step--2);
		letter-spacing: var(--tracking-caps);
		text-transform: uppercase;
	}

	.table td:first-child {
		white-space: nowrap;
	}

	.rules {
		display: grid;
		gap: var(--space-3);
		max-width: var(--measure);
		margin: 0 0 var(--space-5);
		padding-inline-start: var(--space-6);
		line-height: var(--leading-normal);
	}

	.examples {
		display: grid;
		gap: var(--space-4);
		grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr));
	}

	.example {
		display: grid;
		gap: var(--space-3);
		margin: 0;
		padding: var(--space-4);
		background: var(--surface-1);
		border: var(--border);
		border-radius: var(--radius-3);
	}

	.example figcaption {
		max-width: none;
		text-align: start;
	}

	.playground {
		display: grid;
		justify-items: center;
		gap: var(--space-4);
		margin: 0;
		padding: var(--space-5);
		background: var(--surface-1);
		border: var(--border);
		border-radius: var(--radius-3);
	}

	.playground figcaption {
		max-width: var(--measure);
	}

	.chips {
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-2);
	}

	.jumps {
		display: grid;
		gap: var(--space-4);
		grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));
		margin-block: var(--space-7) var(--space-8);
	}

	.jump {
		position: relative;
		display: grid;
		gap: var(--space-1);
		align-content: start;
		padding: var(--space-4) var(--space-6) var(--space-4) var(--space-4);
		background: var(--section-wash);
		border: 1px solid var(--section-edge);
		border-radius: var(--radius-3);
		text-decoration: none;
		color: inherit;
	}

	.jump:hover {
		border-color: var(--section);
	}

	.jump__label {
		font-weight: 620;
	}

	.jump__blurb {
		color: var(--text-muted);
		font-size: var(--step--1);
		line-height: var(--leading-snug);
	}

	.jump__go {
		position: absolute;
		top: var(--space-4);
		inset-inline-end: var(--space-4);
		color: var(--section);
	}
</style>
