/**
 * OLL — orientation of the last layer.
 *
 * All 57 cases, in the order they are worth meeting rather than in numerical
 * order: the seven "corners only" cases first, because they are also the second
 * half of two-look OLL, then the shape families, with the dots last because they
 * are the longest and the rarest.
 *
 * Every case diagram on the site is generated by inverting the *first* algorithm
 * listed, so the picture and the moves can never disagree. Descriptions that say
 * "as drawn" refer to that generated picture: the top face with the back row at
 * the top, the front row at the bottom, and each side face's top strip folded
 * outwards.
 *
 * Probabilities are exact. Of the 216 legal last-layer orientations, 51 cases
 * cover four states each (1/54), five cover two (1/108), and the checkerboard
 * covers one (1/216).
 */

import type { AlgCase } from '../types';

/** Orientation of the last layer — all 57 cases. */
export const OLL_CASES: readonly AlgCase[] = [
	// -------------------------------------------------------------------------
	// All edges oriented — the seven cases two-look OLL finishes with
	// -------------------------------------------------------------------------
	{
		id: 'oll-21',
		set: 'oll',
		name: 'Double Sune',
		shortName: 'OLL 21',
		group: 'All edges oriented',
		tier: 'intermediate',
		algs: [
			{ moves: "R U2 R' U' R U R' U' R U' R'" },
			{ moves: "R U R' U R U' R' U R U2 R'", label: 'alternative' },
			{ moves: "F R U R' U' R U R' U' R U R' U' F'", label: 'F-move' },
			{ moves: "R' U' R U' R' U R U' R' U2 R", label: 'left-hand' }
		],
		probability: '1/108',
		recognition:
			'A bare yellow cross with all four loose corner stickers on the front and back faces, two at each end. Nothing at all shows on the left or the right.',
		notes:
			'Two Sunes in a row solve it, which is where the name comes from; the listed algorithm is that pair with the join cancelled out. The case is symmetric, so two of the four possible starting turns work equally well — there is no recognition to do beyond spotting the bare cross.',
		triggers: ['sexy move', 'Aa insert'],
		tags: ['2-gen', 'one-handed', 'symmetric', 'ocll', 'h-case']
	},
	{
		id: 'oll-22',
		set: 'oll',
		name: 'Pi',
		shortName: 'OLL 22',
		group: 'All edges oriented',
		tier: 'intermediate',
		algs: [
			{ moves: "R U2 R2 U' R2 U' R2 U2 R" },
			{ moves: "R' U2 R2 U R2 U R2 U2 R'", label: 'left-hand' }
		],
		probability: '1/54',
		recognition:
			'A bare cross with two yellow corner stickers sitting together on one side face — the left as drawn — and a single sticker at the far end of both the front and the back.',
		notes:
			'The one two-look case people are slowest to name. Compare it with Double Sune: that has a matching pair on the front *and* the back, while Pi has its pair on one side only. Pure R and U, so it is a fine one-handed case.',
		tags: ['2-gen', 'one-handed', 'ocll', 'pi']
	},
	{
		id: 'oll-23',
		set: 'oll',
		name: 'Headlights',
		shortName: 'OLL 23',
		group: 'All edges oriented',
		tier: 'intermediate',
		algs: [
			{ moves: "R2 D R' U2 R D' R' U2 R'" },
			{ moves: "R2 D' R U2 R' D R U2 R", label: 'mirrored grip' },
			{ moves: "R U R' U R U2 R2 U' R U' R' U2 R", label: '2-gen', note: 'No D turns at all.' }
		],
		probability: '1/54',
		recognition:
			'The cross plus both back corners, so the top shows a solid bar of three across the back. The front face carries a matching pair of yellow stickers — the headlights.',
		notes:
			'Only two corners are wrong and they sit next to each other. Turn the cube so the headlights face you before you start. The D turns are made with the left hand while the right holds the R layer still; if that feels wrong, the 2-gen version avoids them entirely.',
		tags: ['headlights', 'ocll', 'u-case', 'd-moves']
	},
	{
		id: 'oll-24',
		set: 'oll',
		name: 'Chameleon',
		shortName: 'OLL 24',
		group: 'All edges oriented',
		tier: 'intermediate',
		algs: [
			{ moves: "r U R' U' r' F R F'" },
			{ moves: "x' R U R' D R U' R' D'", label: 'rotation' },
			{ moves: "L F R' F' L' F R F'", label: 'two-handed' }
		],
		probability: '1/54',
		recognition:
			'A fat bar down the right of the top face — the cross plus both right-hand corners. One lone yellow sticker sits at the left end of the back row and another at the left end of the front row.',
		notes:
			"Almost exactly OLL 33. Take `R U R' U' R' F R F'`, make the first and fifth moves wide, and you have this. Learning the two together costs very little.",
		triggers: ['sexy move'],
		tags: ['wide-turn', 'ocll', 't-case', 'short']
	},
	{
		id: 'oll-25',
		set: 'oll',
		name: 'Bowtie',
		shortName: 'OLL 25',
		group: 'All edges oriented',
		tier: 'intermediate',
		algs: [
			{ moves: "F' r U R' U' r' F R" },
			{ moves: "R' F R B' R' F' R B", label: 'no wide turns' },
			{ moves: "x' R U' R' D R U R' D'", label: 'rotation' },
			{ moves: "x R' U R D' R' U' R D", label: 'rotation, other grip' }
		],
		probability: '1/54',
		recognition:
			'The cross with two diagonally opposite corners already yellow. The two twisted corners show one sticker on the left face and one at the right-hand end of the front row, pointing away from each other.',
		notes:
			"The awkward one of the seven, and the only one whose finished corners are diagonal. Read the algorithm as F' (r U R' U' r') F R and you will see OLL 24's core sitting inside it.",
		tags: ['diagonal', 'ocll', 'l-case', 'awkward']
	},
	{
		id: 'oll-26',
		set: 'oll',
		name: 'Anti-Sune',
		shortName: 'OLL 26',
		group: 'All edges oriented',
		tier: 'intermediate',
		algs: [
			{ moves: "R U2 R' U' R U' R'" },
			{ moves: "L' U' L U' L' U2 L", label: 'left-hand' },
			{ moves: "R' U' R U' R' U2 R", label: 'reverse grip' }
		],
		probability: '1/54',
		recognition:
			'The cross with exactly one corner already yellow. As drawn the finished corner is at the back right, and the other three show their yellow on the left face, at the left end of the front, and at the front end of the right face.',
		notes:
			'The mirror of Sune and the case most often confused with it. Hold the finished corner at the front left: the corner diagonally opposite then shows yellow on the back for Anti-Sune, and on the right for Sune.',
		triggers: ['Aa insert'],
		mirrorOf: 'oll-27',
		tags: ['2-gen', 'one-handed', 'ocll', 'sune-family', 'mirror', 'short']
	},
	{
		id: 'oll-27',
		set: 'oll',
		name: 'Sune',
		shortName: 'OLL 27',
		group: 'All edges oriented',
		tier: 'intermediate',
		algs: [
			{ moves: "R U R' U R U2 R'" },
			{ moves: "L' U2 L U L' U L", label: 'left-hand' },
			{ moves: "R' U2 R U R' U R", label: 'reverse grip' },
			{ moves: "L U L' U L U2 L'", label: 'left-hand, other grip' }
		],
		probability: '1/54',
		recognition:
			'The cross with exactly one corner already yellow. As drawn the finished corner is at the front left, and the other three show yellow on the back face, on the right face and on the front face in turn.',
		notes:
			'The first algorithm most people learn past the beginner method, and the backbone of half of OLL. Hold the finished corner at the front left and look at the corner diagonally opposite it: yellow on the right means Sune, yellow on the back means Anti-Sune.',
		triggers: ['sune'],
		mirrorOf: 'oll-26',
		tags: ['2-gen', 'one-handed', 'ocll', 'sune-family', 'mirror', 'fast', 'short']
	},

	// -------------------------------------------------------------------------
	// T shapes
	// -------------------------------------------------------------------------
	{
		id: 'oll-33',
		set: 'oll',
		name: 'Key',
		shortName: 'OLL 33',
		group: 'T shapes',
		tier: 'advanced',
		algs: [{ moves: "R U R' U' R' F R F'" }, { moves: "L' U' L U L F' L' F", label: 'left-hand' }],
		probability: '1/54',
		recognition:
			'A sideways T: the whole right-hand column of the top face plus the middle row reaching across to the left. The back and the front each show two yellow stickers running from the left corner to the middle.',
		notes:
			'Sexy move straight into a sledgehammer and nothing else — the shortest useful pairing of the two triggers, and worth drilling for its own sake. OLL 24 is this same algorithm with two turns made wide.',
		triggers: ['sexy move', 'sledgehammer'],
		tags: ['short', 'fast', 'trigger-pair', 't-shape']
	},
	{
		id: 'oll-45',
		set: 'oll',
		name: 'T Shape',
		shortName: 'OLL 45',
		group: 'T shapes',
		tier: 'advanced',
		algs: [
			{ moves: "F R U R' U' F'" },
			{ moves: "f U R U' R' f'", label: 'wide-turn' },
			{ moves: "F' L' U' L U F", label: 'left-hand' },
			{ moves: "R' F' U' F U R", label: 'reverse grip' }
		],
		probability: '1/54',
		recognition:
			'The same sideways T as OLL 33, but the two loose corner stickers both face left, one at each end of the left face, instead of splitting between the front and the back.',
		notes:
			'Six moves, and you almost certainly know them already: this is the "line" algorithm of two-look edge orientation, arriving here with the corners happening to fall right.',
		triggers: ['sexy move'],
		tags: ['short', 'fast', 'two-look', 't-shape']
	},

	// -------------------------------------------------------------------------
	// Squares
	// -------------------------------------------------------------------------
	{
		id: 'oll-05',
		set: 'oll',
		name: 'Left Square',
		shortName: 'OLL 5',
		group: 'Squares',
		tier: 'advanced',
		algs: [
			{ moves: "r' U2 R U R' U r" },
			{ moves: "l' U2 L U L' U l", label: 'left-hand' },
			{ moves: "R' F2 r U r' F R", label: 'F-move' }
		],
		probability: '1/54',
		recognition:
			'A 2×2 block of yellow filling one corner of the top face — the front right as drawn — with the loose stickers wrapping round the left face and along the back.',
		notes:
			"The mirror of OLL 6. Both are a single wide turn either side of a short body, which makes them two of the cheapest cases in the set to pick up: r' opens this one, r opens its mirror.",
		mirrorOf: 'oll-06',
		tags: ['wide-turn', 'short', 'mirror', 'square', 'lefty']
	},
	{
		id: 'oll-06',
		set: 'oll',
		name: 'Right Square',
		shortName: 'OLL 6',
		group: 'Squares',
		tier: 'advanced',
		algs: [{ moves: "r U2 R' U' R U' r'" }, { moves: "l U2 L' U' L U' l'", label: 'left-hand' }],
		probability: '1/54',
		recognition:
			'The mirror of OLL 5: a 2×2 block of yellow, drawn here at the back right, with the loose stickers running down the left face and along the front.',
		notes:
			'Seven moves in one grip and comfortable one-handed. If you keep confusing it with OLL 5, look at which side face carries two of the loose stickers and which carries one.',
		mirrorOf: 'oll-05',
		tags: ['wide-turn', 'short', 'mirror', 'square', 'one-handed']
	},

	// -------------------------------------------------------------------------
	// C shapes
	// -------------------------------------------------------------------------
	{
		id: 'oll-34',
		set: 'oll',
		name: 'C Shape (back)',
		shortName: 'OLL 34',
		group: 'C shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U R2 U' R' F R U R U' F'" },
			{ moves: "R U R' U' B' R' F R F' B", label: 'B-move' },
			{ moves: "f R f' U' r' U' R U M'", label: 'slice' }
		],
		probability: '1/54',
		recognition:
			'A C opening towards the back: the middle row of the top face plus both front corners. Single yellow stickers sit at the back end of the left and right faces.',
		notes:
			'The two finished corners at the front read as headlights. Check that the middle row is complete before committing — if one edge is missing you are looking at a P shape instead.',
		tags: ['c-shape', 'headlights']
	},
	{
		id: 'oll-46',
		set: 'oll',
		name: 'C Shape (right)',
		shortName: 'OLL 46',
		group: 'C shapes',
		tier: 'advanced',
		algs: [{ moves: "R' U' R' F R F' U R" }, { moves: "L U L F' L' F U' L'", label: 'left-hand' }],
		probability: '1/54',
		recognition:
			'A C opening to the right: both left-hand corners with the front and back edges, but not the left edge. The whole right face shows yellow, three stickers in a column.',
		notes:
			"Eight moves and nearly all right hand — R' then a sledgehammer then U R. One of the friendliest algorithms in the set, and a good early one to learn.",
		triggers: ['sledgehammer'],
		tags: ['c-shape', 'short', 'one-handed', 'fast']
	},

	// -------------------------------------------------------------------------
	// W shapes
	// -------------------------------------------------------------------------
	{
		id: 'oll-36',
		set: 'oll',
		name: 'W Shape (left)',
		shortName: 'OLL 36',
		group: 'W shapes',
		tier: 'advanced',
		algs: [
			{ moves: "L' U' L U' L' U L U L F' L' F" },
			{ moves: "R' U' R U' R' U R U R B' R' B", label: 'right-hand, B-move' },
			{ moves: "R U R2 F' U' F U R2 U2 R'", label: 'shorter' }
		],
		probability: '1/54',
		recognition:
			'A staircase of yellow running from the back-left corner across to the front-right: corner, edge, centre, edge, corner. The left face shows two stickers and the back one.',
		notes:
			'The mirror of OLL 38, and the pair are easy to swap by accident. Trace the staircase and see which diagonal it runs along before you start.',
		mirrorOf: 'oll-38',
		tags: ['w-shape', 'mirror', 'lefty']
	},
	{
		id: 'oll-38',
		set: 'oll',
		name: 'W Shape (right)',
		shortName: 'OLL 38',
		group: 'W shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U R' U R U' R' U' R' F R F'" },
			{ moves: "L U L' U L U' L' U' L' B L B'", label: 'left-hand, B-move' }
		],
		probability: '1/54',
		recognition:
			'The mirror staircase: yellow runs from the back-right corner down to the front-left. The right face shows two stickers and the back one.',
		notes:
			'Sexy move, then its reverse, then a sledgehammer — three familiar pieces in a row, which is why most people find this the easier half of the pair.',
		triggers: ['Aa insert', 'sledgehammer'],
		mirrorOf: 'oll-36',
		tags: ['w-shape', 'mirror', 'trigger-pair']
	},

	// -------------------------------------------------------------------------
	// Corners oriented
	// -------------------------------------------------------------------------
	{
		id: 'oll-28',
		set: 'oll',
		name: 'Stealth',
		shortName: 'OLL 28',
		group: 'Corners oriented',
		tier: 'advanced',
		algs: [
			{ moves: "r U R' U' r' R U R U' R'" },
			{ moves: "M' U M U2 M' U M", label: 'slice', note: 'Seven moves, all M and U.' },
			{ moves: "R' F R S R' F' R S'", label: 'S-move' }
		],
		probability: '1/54',
		recognition:
			'Every corner is already yellow. Two adjacent edges are flipped — the right and the front as drawn — leaving a square of seven stickers with a bite out of one side.',
		notes:
			'Only two edges to fix, so it should be fast. The pure slice version is lovely once M turns feel natural, and it is the same seven moves whichever way round you hold the case.',
		triggers: ['Aa insert'],
		tags: ['corners-done', 'slice', 'short', 'fast']
	},
	{
		id: 'oll-57',
		set: 'oll',
		name: 'Corners Done, Bar',
		shortName: 'OLL 57',
		group: 'Corners oriented',
		tier: 'advanced',
		algs: [
			{ moves: "R U R' U' M' U R U' r'" },
			{ moves: "M' U M' U M' U2 M U M U M U2", label: 'slice' },
			{ moves: "R U R' U' r R' U R U' r'", label: 'wide-turn' },
			{ moves: "M U M U M U2 M' U M' U M' U2", label: 'slice, other direction' }
		],
		probability: '1/108',
		recognition:
			'All four corners done and a bar of three across the middle of the top: only the front and back edges are flipped.',
		notes:
			"Two opposite edges to swap over and nothing else. Read it as sexy move, M', then U R U' r' — the wide finish is what puts the M slice back where it started. One of the six rarest cases.",
		triggers: ['sexy move'],
		tags: ['corners-done', 'slice', 'rare', 'short']
	},

	// -------------------------------------------------------------------------
	// P shapes
	// -------------------------------------------------------------------------
	{
		id: 'oll-31',
		set: 'oll',
		name: 'P Shape (back)',
		shortName: 'OLL 31',
		group: 'P shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R' U' F U R U' R' F' R" },
			{ moves: "L' U' B U L U' L' B' L", label: 'left-hand, B-move' },
			{ moves: "S' L' U' L U L F' L' f", label: 'slice' }
		],
		probability: '1/54',
		recognition:
			'A P lying on its side: the right-hand column of the top face plus the centre and the back edge. The front shows two yellow stickers at its left end.',
		notes:
			'Nine moves, mostly right hand with one F. The mirror is OLL 32; the difference is whether the extra edge is at the back or the front.',
		triggers: ['Aa insert'],
		mirrorOf: 'oll-32',
		tags: ['p-shape', 'mirror']
	},
	{
		id: 'oll-32',
		set: 'oll',
		name: 'P Shape (front)',
		shortName: 'OLL 32',
		group: 'P shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U B' U' R' U R B R'" },
			{ moves: "S R U R' U' R' F R f'", label: 'slice' },
			{ moves: "L U F' U' L' U L F L'", label: 'left-hand, F-move' }
		],
		probability: '1/54',
		recognition:
			'The mirror of OLL 31: the right-hand column of the top face with the centre and the front edge, and two yellow stickers on the back at its left end.',
		notes:
			'The listed algorithm uses B turns, which many people dislike; the slice version keeps everything at the front if you would rather.',
		mirrorOf: 'oll-31',
		tags: ['p-shape', 'mirror', 'b-moves']
	},
	{
		id: 'oll-43',
		set: 'oll',
		name: 'P Shape (left)',
		shortName: 'OLL 43',
		group: 'P shapes',
		tier: 'advanced',
		algs: [
			{ moves: "f' L' U' L U f" },
			{ moves: "B' U' R' U R B", label: 'B-move' },
			{ moves: "R' U' F' U F R", label: 'right-hand' },
			{ moves: "F' U' L' U L F", label: 'F-move' }
		],
		probability: '1/54',
		recognition:
			'The left-hand column of the top face plus the front edge — a P facing left. The whole right face shows yellow.',
		notes:
			'Six moves, and the mirror of OLL 44. Both are the L-shape of two-look edge orientation arriving with the corners already sorted, so the fingers should be familiar.',
		mirrorOf: 'oll-44',
		tags: ['p-shape', 'short', 'mirror', 'wide-turn', 'lefty', 'fast']
	},
	{
		id: 'oll-44',
		set: 'oll',
		name: 'P Shape (right)',
		shortName: 'OLL 44',
		group: 'P shapes',
		tier: 'advanced',
		algs: [
			{ moves: "f R U R' U' f'" },
			{ moves: "F U R U' R' F'", label: 'no wide turns' },
			{ moves: "B U L U' L' B'", label: 'B-move' }
		],
		probability: '1/54',
		recognition:
			'The right-hand column of the top face plus the front edge — a P facing right. The whole left face shows yellow.',
		notes:
			'Six moves and one of the first two you should learn: it is exactly the algorithm you already use for the L shape in two-look edge orientation.',
		triggers: ['sexy move'],
		mirrorOf: 'oll-43',
		tags: ['p-shape', 'short', 'mirror', 'wide-turn', 'two-look', 'fast']
	},

	// -------------------------------------------------------------------------
	// I shapes
	// -------------------------------------------------------------------------
	{
		id: 'oll-51',
		set: 'oll',
		name: 'Bottlecap',
		shortName: 'OLL 51',
		group: 'I shapes',
		tier: 'advanced',
		algs: [
			{ moves: "f R U R' U' R U R' U' f'" },
			{ moves: "F U R U' R' U R U' R' F'", label: 'no wide turns' },
			{ moves: "R' U' R' F R F' R U' R' U2 R", label: 'right-hand' }
		],
		probability: '1/54',
		recognition:
			'A bare line of three across the middle of the top face, no corners at all. The left face carries a sticker at each end and the front and back each show a pair at their right.',
		notes:
			"Double sexy inside a wide f … f'. If OLL 44 is already in your hands, this is the same wrapper with the sexy move done twice.",
		triggers: ['sexy move', 'double sexy'],
		tags: ['i-shape', 'line', 'wide-turn', 'no-corners']
	},
	{
		id: 'oll-52',
		set: 'oll',
		name: 'Rice Cooker',
		shortName: 'OLL 52',
		group: 'I shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U R' U R U' B U' B' R'" },
			{ moves: "R' F' U' F U' R U R' U R", label: 'F-move' },
			{ moves: "R U R' U R d' R U' R' F'", label: 'wide-turn' },
			{ moves: "L' B' U' B U' L U L' U L", label: 'left-hand' }
		],
		probability: '1/54',
		recognition:
			'A bare line running front to back. The right face shows a full column of yellow while the left shows only its middle sticker.',
		notes:
			'The B turns are unusual in a right-hand algorithm; the F-move version avoids them if you would rather keep everything in front of you.',
		tags: ['i-shape', 'line', 'b-moves', 'no-corners']
	},
	{
		id: 'oll-55',
		set: 'oll',
		name: 'Highway',
		shortName: 'OLL 55',
		group: 'I shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U2 R2 U' R U' R' U2 F R F'" },
			{ moves: "R' F R U R U' R2 F' R2 U' R' U R U R'", label: 'longer, easier' },
			{ moves: "r U2 R2 F R F' U2 r' F R F'", label: 'wide-turn' }
		],
		probability: '1/108',
		recognition:
			'A bare line front to back with the left and right faces each showing a full column of yellow, and nothing at all on the front or the back.',
		notes:
			'One of the six rarest cases. The short version needs a confident R U2 R2; the longer alternative is friendlier to learn even though it costs five more moves.',
		triggers: ['Aa insert'],
		tags: ['i-shape', 'line', 'rare', 'no-corners']
	},
	{
		id: 'oll-56',
		set: 'oll',
		name: 'Streetlights',
		shortName: 'OLL 56',
		group: 'I shapes',
		tier: 'advanced',
		algs: [
			{ moves: "r U r' U R U' R' U R U' R' r U' r'" },
			{ moves: "F R U R' U' R F' r U R' U' r'", label: 'shorter' },
			{ moves: "r' U' r U' R' U R U' R' U R r' U r", label: 'left-hand grip' }
		],
		probability: '1/108',
		recognition:
			'A bare line left to right, with a yellow corner sticker at each end of the left face and each end of the right face.',
		notes:
			'Rare and genuinely awkward: three wide turns wrapped round a double sexy. Take it slowly the first few dozen times — rushing it is how you drop the cube.',
		triggers: ['Aa insert'],
		tags: ['i-shape', 'line', 'rare', 'wide-turn', 'awkward', 'no-corners']
	},

	// -------------------------------------------------------------------------
	// Fish shapes
	// -------------------------------------------------------------------------
	{
		id: 'oll-09',
		set: 'oll',
		name: 'Kite',
		shortName: 'OLL 9',
		group: 'Fish shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U R' U' R' F R2 U R' U' F'" },
			{ moves: "R' U' R U' R' U R' F R F' U R", label: 'sledgehammer' },
			{ moves: "F' U' F r U' r' U r U r'", label: 'wide-turn' }
		],
		probability: '1/54',
		recognition:
			'A kite: the back and left edges with the centre, and a lone corner diagonally across at the front right.',
		notes:
			'The mirror of OLL 10 and usually learnt with it — the same shape, opposite hands. The giveaway is which pair of edges is up.',
		triggers: ['sexy move'],
		mirrorOf: 'oll-10',
		tags: ['fish', 'kite', 'mirror']
	},
	{
		id: 'oll-10',
		set: 'oll',
		name: 'Anti-Kite',
		shortName: 'OLL 10',
		group: 'Fish shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U R' U R' F R F' R U2 R'" },
			{ moves: "R U R' y R' F R U' R' F' R", label: 'rotation' },
			{ moves: "F U F' R' F R U' R' F' R", label: 'no rotation' }
		],
		probability: '1/54',
		recognition:
			'The mirror kite: the left and front edges with the centre, and the lone corner at the back right.',
		notes: "A sledgehammer in the middle and a Sune-like R U2 R' to finish. Mirror of OLL 9.",
		triggers: ['sledgehammer'],
		mirrorOf: 'oll-09',
		tags: ['fish', 'kite', 'mirror']
	},
	{
		id: 'oll-35',
		set: 'oll',
		name: 'Fish Salad',
		shortName: 'OLL 35',
		group: 'Fish shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U2 R2 F R F' R U2 R'" },
			{ moves: "L' U2 L2 F' L' F L' U2 L", label: 'left-hand' },
			{ moves: "f R U R' U' f' R U R' U R U2 R'", label: 'two-look style' }
		],
		probability: '1/54',
		recognition:
			'A fish pointing at the front-right corner: that corner with the two edges beside it and the centre, plus a lone corner away at the back left.',
		notes:
			"Reads as two half-Sunes wrapped round an F R F'. Nine moves, all right hand, and quick once the R2 in the middle stops feeling loose.",
		tags: ['fish', 'fast']
	},
	{
		id: 'oll-37',
		set: 'oll',
		name: 'Mounted Fish',
		shortName: 'OLL 37',
		group: 'Fish shapes',
		tier: 'advanced',
		algs: [{ moves: "F R' F' R U R U' R'" }, { moves: "F R U' R' U' R U R' F'", label: 'longer' }],
		probability: '1/54',
		recognition:
			'A fish pointing at the back-left corner: that corner with the two edges beside it, and a lone corner at the front right. The right face shows two stickers.',
		notes:
			'Hedgeslammer straight into an insert — eight moves, and one of the quickest cases in the whole set once the two triggers are automatic.',
		triggers: ['hedgeslammer', 'Aa insert'],
		tags: ['fish', 'fast', 'short', 'trigger-pair']
	},

	// -------------------------------------------------------------------------
	// Knight move shapes
	// -------------------------------------------------------------------------
	{
		id: 'oll-13',
		set: 'oll',
		name: 'Knight Move (front-left)',
		shortName: 'OLL 13',
		group: 'Knight move shapes',
		tier: 'advanced',
		algs: [
			{ moves: "F U R U' R2 F' R U R U' R'" },
			{ moves: "r U' r' U' r U r' F' U F", label: 'wide-turn' },
			{ moves: "r U' r' U' r U r' y' R' U R", label: 'rotation' }
		],
		probability: '1/54',
		recognition:
			"A bar across the middle of the top face with one extra corner hanging off it at the front left — a knight's move away from the far end of the bar.",
		notes:
			'The wide-turn version is much smoother than the F-move one if your hands already know the r grip. Mirror of OLL 14.',
		triggers: ['Aa insert'],
		mirrorOf: 'oll-14',
		tags: ['knight', 'mirror', 'wide-turn']
	},
	{
		id: 'oll-14',
		set: 'oll',
		name: 'Knight Move (front-right)',
		shortName: 'OLL 14',
		group: 'Knight move shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R' F R U R' F' R F U' F'" },
			{ moves: "r' U r U r' U' r y R U' R'", label: 'wide-turn, rotation' },
			{ moves: "F' U' L' U L2 F L' U' L' U L", label: 'left-hand' }
		],
		probability: '1/54',
		recognition: 'The same middle bar as OLL 13, with the extra corner at the front right instead.',
		notes:
			'Mirror of OLL 13. All four knight-move cases share the bar; the whole recognition is which corner is attached and where the loose side stickers sit.',
		mirrorOf: 'oll-13',
		tags: ['knight', 'mirror']
	},
	{
		id: 'oll-15',
		set: 'oll',
		name: 'Knight Move (back-left)',
		shortName: 'OLL 15',
		group: 'Knight move shapes',
		tier: 'advanced',
		algs: [
			{ moves: "l' U' l L' U' L U l' U l" },
			{ moves: "r' U' r R' U' R U r' U r", label: 'right-hand grip' },
			{ moves: "R' F' R L' U' L U R' F R", label: 'no wide turns' }
		],
		probability: '1/54',
		recognition:
			'The middle bar with its extra corner at the back left. The back face shows only its middle sticker, which is what separates it from OLL 13.',
		notes:
			'Mirror of OLL 16, and the pair are both short. The wide turn and the plain turn alternate, so count carefully the first few times.',
		mirrorOf: 'oll-16',
		tags: ['knight', 'mirror', 'wide-turn', 'lefty']
	},
	{
		id: 'oll-16',
		set: 'oll',
		name: 'Knight Move (back-right)',
		shortName: 'OLL 16',
		group: 'Knight move shapes',
		tier: 'advanced',
		algs: [
			{ moves: "r U r' R U R' U' r U' r'" },
			{ moves: "l U l' L U L' U' l U' l'", label: 'left-hand' }
		],
		probability: '1/54',
		recognition: 'The middle bar with its extra corner at the back right.',
		notes:
			'A wide sexy move wrapped round a plain one. Mirror of OLL 15 and the friendlier of the two for most right-handers.',
		triggers: ['sexy move'],
		mirrorOf: 'oll-15',
		tags: ['knight', 'mirror', 'wide-turn']
	},

	// -------------------------------------------------------------------------
	// Awkward shapes
	// -------------------------------------------------------------------------
	{
		id: 'oll-29',
		set: 'oll',
		name: 'Awkward (right)',
		shortName: 'OLL 29',
		group: 'Awkward shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U R' U' R U' R' F' U' F R U R'" },
			{ moves: "M U R U R' U' R' F R F' M'", label: 'slice', note: 'Two moves shorter.' },
			{ moves: "r2 D' r U r' D r2 U' r' U' r", label: 'wide-turn' },
			{ moves: "R' F R F' R U2 R' U' F' U' F", label: 'sledgehammer opening' }
		],
		probability: '1/54',
		recognition:
			'An awkward scatter with no clean shape to it: the back and left edges, the back-right corner and the front-right corner.',
		notes:
			'Thirteen moves in the standard form, which is why the slice version is worth the effort if M turns are comfortable. Mirror of OLL 30.',
		triggers: ['sexy move', 'Aa insert'],
		mirrorOf: 'oll-30',
		tags: ['awkward', 'mirror', 'long']
	},
	{
		id: 'oll-30',
		set: 'oll',
		name: 'Awkward (left)',
		shortName: 'OLL 30',
		group: 'Awkward shapes',
		tier: 'advanced',
		algs: [
			{ moves: "F R' F R2 U' R' U' R U R' F2" },
			{ moves: "R2 U R' B' R U' R2 U R B R'", label: 'B-move' },
			{ moves: "M U' L' U' L U L F' L' F M'", label: 'slice' },
			{ moves: "F U R U2 R' U' R U2 R' U' F'", label: 'F-move' }
		],
		probability: '1/54',
		recognition: 'The mirror awkward case: the back and left edges plus both front corners.',
		notes:
			'The F2 at the end is a half turn, not a typo — it is the most common place to go wrong. Mirror of OLL 29.',
		mirrorOf: 'oll-29',
		tags: ['awkward', 'mirror']
	},
	{
		id: 'oll-41',
		set: 'oll',
		name: 'Awkward Fish (right)',
		shortName: 'OLL 41',
		group: 'Awkward shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R U R' U R U2 R' F R U R' U' F'" },
			{ moves: "L U L' U L U2 L' F' L' U' L U F", label: 'left-hand' },
			{ moves: "f R U R' U' f' U' R U R' U R U2 R'", label: 'T shape first' }
		],
		probability: '1/54',
		recognition:
			'The back edge, the left edge and both front corners on top. The same top-face shape as OLL 30, but here the two loose corner stickers sit at either end of the back face.',
		notes:
			'A Sune straight into the six-move T algorithm — two things you already know, joined end to end. Mirror of OLL 42.',
		triggers: ['sune', 'sexy move'],
		mirrorOf: 'oll-42',
		tags: ['awkward', 'mirror', 'trigger-pair', 'long']
	},
	{
		id: 'oll-42',
		set: 'oll',
		name: 'Awkward Fish (left)',
		shortName: 'OLL 42',
		group: 'Awkward shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R' U' R U' R' U2 R F R U R' U' F'" },
			{ moves: "L' U' L U' L' U2 L F' L' U' L U F", label: 'left-hand' }
		],
		probability: '1/54',
		recognition:
			'Both back corners with the left and front edges. The two loose corner stickers sit at either end of the front face.',
		notes:
			'An Anti-Sune into the same six-move T algorithm, so it mirrors OLL 41 in structure as well as in shape.',
		triggers: ['sexy move'],
		mirrorOf: 'oll-41',
		tags: ['awkward', 'mirror', 'trigger-pair', 'long']
	},

	// -------------------------------------------------------------------------
	// L shapes
	// -------------------------------------------------------------------------
	{
		id: 'oll-47',
		set: 'oll',
		name: 'L Shape (double sledgehammer)',
		shortName: 'OLL 47',
		group: 'L shapes',
		tier: 'advanced',
		algs: [
			{ moves: "R' U' R' F R F' R' F R F' U R" },
			{ moves: "F' L' U' L U L' U' L U F", label: 'left-hand' },
			{ moves: "b' U' R' U R U' R' U R b", label: 'wide-turn' }
		],
		probability: '1/54',
		recognition:
			'No corners at all: the back and right edges with the centre, making an L. The front face shows two yellow stickers at its left end.',
		notes: "Two sledgehammers back to back with an R' in front and a U R behind. Mirror of OLL 48.",
		triggers: ['sledgehammer'],
		mirrorOf: 'oll-48',
		tags: ['l-shape', 'mirror', 'no-corners', 'trigger-pair']
	},
	{
		id: 'oll-48',
		set: 'oll',
		name: 'Breakneck',
		shortName: 'OLL 48',
		group: 'L shapes',
		tier: 'advanced',
		algs: [
			{ moves: "F R U R' U' R U R' U' F'" },
			{ moves: "R U2 R' U' R U R' U2 R' F R F'", label: '2-gen opening' }
		],
		probability: '1/54',
		recognition:
			'The mirror L: the back and left edges with the centre, and two yellow stickers on the front at its right end.',
		notes:
			"Double sexy inside F … F'. Ten moves that feel like six once the sexy move runs itself. Mirror of OLL 47.",
		triggers: ['sexy move', 'double sexy'],
		mirrorOf: 'oll-47',
		tags: ['l-shape', 'mirror', 'no-corners', 'fast']
	},
	{
		id: 'oll-49',
		set: 'oll',
		name: 'L Shape (back-right)',
		shortName: 'OLL 49',
		group: 'L shapes',
		tier: 'advanced',
		algs: [
			{ moves: "r U' r2 U r2 U r2 U' r" },
			{ moves: "R B' R2 F R2 B R2 F' R", label: 'no wide turns' },
			{ moves: "l U' l2 U l2 U l2 U' l", label: 'left-hand' }
		],
		probability: '1/54',
		recognition:
			'The same L as OLL 47 — the back and right edges with the centre — but here the whole left face shows yellow.',
		notes:
			'Nine moves of nothing but r and U. Once the r2 is comfortable this is among the fastest cases in the set. Mirror of OLL 50.',
		mirrorOf: 'oll-50',
		tags: ['l-shape', 'mirror', 'wide-turn', 'no-corners', 'fast']
	},
	{
		id: 'oll-50',
		set: 'oll',
		name: 'L Shape (front-right)',
		shortName: 'OLL 50',
		group: 'L shapes',
		tier: 'advanced',
		algs: [
			{ moves: "r' U r2 U' r2 U' r2 U r'" },
			{ moves: "R' F R2 B' R2 F' R2 B R'", label: 'no wide turns' },
			{ moves: "l' U l2 U' l2 U' l2 U l'", label: 'left-hand' },
			{ moves: "R U2 R' U' R U' R' F R U R' U' F'", label: 'Anti-Sune first' }
		],
		probability: '1/54',
		recognition:
			'An L made of the right and front edges with the centre, and the whole left face showing yellow.',
		notes:
			"Mirror of OLL 49, done with r' instead of r. Same shape of algorithm, opposite direction.",
		mirrorOf: 'oll-49',
		tags: ['l-shape', 'mirror', 'wide-turn', 'no-corners']
	},
	{
		id: 'oll-53',
		set: 'oll',
		name: 'Frying Pan (left)',
		shortName: 'OLL 53',
		group: 'L shapes',
		tier: 'advanced',
		algs: [
			{ moves: "r' U' R U' R' U R U' R' U2 r" },
			{ moves: "l' U' L U' L' U L U' L' U2 l", label: 'left-hand' },
			{ moves: "r' U2 R U R' U' R U R' U r", label: 'other direction' }
		],
		probability: '1/54',
		recognition:
			'The right and front edges with the centre. The left face is a full column of yellow and the right face shows a sticker at each end.',
		notes:
			'Ten moves but all in one grip, which makes it much easier than the count suggests. Mirror of OLL 54.',
		triggers: ['Aa insert'],
		mirrorOf: 'oll-54',
		tags: ['l-shape', 'mirror', 'wide-turn', 'no-corners', 'lefty']
	},
	{
		id: 'oll-54',
		set: 'oll',
		name: 'Frying Pan (right)',
		shortName: 'OLL 54',
		group: 'L shapes',
		tier: 'advanced',
		algs: [
			{ moves: "r U R' U R U' R' U R U2 r'" },
			{ moves: "l U L' U L U' L' U L U2 l'", label: 'left-hand' },
			{ moves: "r U2 R' U' R U R' U' R U' r'", label: 'other direction' }
		],
		probability: '1/54',
		recognition:
			'The back and right edges with the centre, the left face a full column of yellow and the right face a sticker at each end.',
		notes:
			'Mirror of OLL 53, in the right-hand grip. Compare the two side faces to tell them apart.',
		triggers: ['Aa insert'],
		mirrorOf: 'oll-53',
		tags: ['l-shape', 'mirror', 'wide-turn', 'no-corners']
	},

	// -------------------------------------------------------------------------
	// Lightning bolts
	// -------------------------------------------------------------------------
	{
		id: 'oll-07',
		set: 'oll',
		name: 'Lightning (right)',
		shortName: 'OLL 7',
		group: 'Lightning bolts',
		tier: 'advanced',
		algs: [
			{ moves: "r U R' U R U2 r'" },
			{ moves: "F R' F' R U2 R U2 R'", label: 'no wide turns' }
		],
		probability: '1/54',
		recognition:
			'A lightning bolt: the back and left edges with the centre, and the front-left corner hanging off the end.',
		notes:
			'Seven moves. The wide turns at either end do all the awkward work and the middle is a plain Sune, so it is really the Sune you already know. Mirror of OLL 8.',
		mirrorOf: 'oll-08',
		tags: ['lightning', 'mirror', 'wide-turn', 'short', 'fast']
	},
	{
		id: 'oll-08',
		set: 'oll',
		name: 'Lightning (left)',
		shortName: 'OLL 8',
		group: 'Lightning bolts',
		tier: 'advanced',
		algs: [{ moves: "r' U' R U' R' U2 r" }, { moves: "l' U' L U' L' U2 l", label: 'left-hand' }],
		probability: '1/54',
		recognition:
			'The mirror bolt: the left and front edges with the centre and the back-left corner.',
		notes: 'An Anti-Sune between two wide turns. Mirror of OLL 7 and equally short.',
		mirrorOf: 'oll-07',
		tags: ['lightning', 'mirror', 'wide-turn', 'short', 'fast', 'lefty']
	},
	{
		id: 'oll-11',
		set: 'oll',
		name: 'Lightning (back-right)',
		shortName: 'OLL 11',
		group: 'Lightning bolts',
		tier: 'advanced',
		algs: [
			{ moves: "r U R' U R' F R F' R U2 r'" },
			{ moves: "r' R2 U R' U R U2 R' U M'", label: 'slice' },
			{ moves: "M R U R' U R U2 R' U M'", label: 'slice, M start' }
		],
		probability: '1/54',
		recognition:
			'A bolt running from the back-right corner along the back edge, through the centre and out to the left edge.',
		notes:
			'The sledgehammer sits in the middle of a wide-turn shell. Mirror of OLL 12 and the easier of the pair for most right-handers.',
		triggers: ['sledgehammer'],
		mirrorOf: 'oll-12',
		tags: ['lightning', 'mirror', 'wide-turn']
	},
	{
		id: 'oll-12',
		set: 'oll',
		name: 'Lightning (back-left)',
		shortName: 'OLL 12',
		group: 'Lightning bolts',
		tier: 'advanced',
		algs: [
			{ moves: "l' U' L U' L F' L' F L' U2 l" },
			{ moves: "M' R' U' R U' R' U2 R U' R r'", label: 'slice' },
			{ moves: "F R U R' U' F' U F R U R' U' F'", label: 'two-look style' }
		],
		probability: '1/54',
		recognition:
			'The mirror bolt: from the back-left corner along the back edge, through the centre and out to the right edge.',
		notes:
			'Written left-handed here so it matches OLL 11 move for move. The two-look version is longer but uses only algorithms you already have.',
		mirrorOf: 'oll-11',
		tags: ['lightning', 'mirror', 'wide-turn', 'lefty']
	},
	{
		id: 'oll-39',
		set: 'oll',
		name: 'Big Lightning (left)',
		shortName: 'OLL 39',
		group: 'Lightning bolts',
		tier: 'advanced',
		algs: [
			{ moves: "L F' L' U' L U F U' L'" },
			{ moves: "R B' R' U' R U B U' R'", label: 'right-hand, B-move' },
			{ moves: "f' r U r' U' r' F r S", label: 'slice' }
		],
		probability: '1/54',
		recognition:
			'A big lightning bolt: the whole middle row of the top face with one corner at each end, going opposite ways — back right and front left.',
		notes: 'Nine moves and mostly left hand as written. Mirror of OLL 40.',
		mirrorOf: 'oll-40',
		tags: ['lightning', 'big-lightning', 'mirror', 'lefty']
	},
	{
		id: 'oll-40',
		set: 'oll',
		name: 'Big Lightning (right)',
		shortName: 'OLL 40',
		group: 'Lightning bolts',
		tier: 'advanced',
		algs: [
			{ moves: "R' F R U R' U' F' U R" },
			{ moves: "L' B L U L' U' B' U L", label: 'left-hand, B-move' }
		],
		probability: '1/54',
		recognition: 'The mirror big bolt: the middle row with the back-left and front-right corners.',
		notes: 'Mirror of OLL 39, in the right-hand grip, and one move shorter to reach for.',
		mirrorOf: 'oll-39',
		tags: ['lightning', 'big-lightning', 'mirror']
	},

	// -------------------------------------------------------------------------
	// Dots — no edges oriented at all
	// -------------------------------------------------------------------------
	{
		id: 'oll-01',
		set: 'oll',
		name: 'Runway',
		shortName: 'OLL 1',
		group: 'Dots',
		tier: 'advanced',
		algs: [
			{ moves: "R U2 R2 F R F' U2 R' F R F'" },
			{ moves: "R U B' R B R2 U' R' F R F'", label: 'B-move' }
		],
		probability: '1/108',
		recognition:
			'A bare dot with a full column of yellow down both the left and the right faces. The front and back each show only their middle sticker.',
		notes:
			'The corners are twisted exactly as they are in Double Sune, so once the edges are up you would be looking at OLL 21. One of the six rarest cases, which is fair reason to leave it until last.',
		triggers: ['sledgehammer'],
		tags: ['dot', 'rare', 'long', 'no-edges']
	},
	{
		id: 'oll-02',
		set: 'oll',
		name: 'Zamboni',
		shortName: 'OLL 2',
		group: 'Dots',
		tier: 'advanced',
		algs: [
			{ moves: "F R U R' U' F' f R U R' U' f'" },
			{ moves: "r U r' U2 R U2 R' U2 r U' r'", label: 'wide-turn' },
			{ moves: "F R U R' U' S R U R' U' f'", label: 'slice' }
		],
		probability: '1/54',
		recognition:
			'A dot with a full column of yellow down the left face only. The back and the front each show a pair of stickers at their right-hand ends.',
		notes:
			'The listed algorithm is the two-look dot: the line algorithm and the L-shape algorithm run back to back. You already know it, which makes this the friendliest dot to meet first. The corners are twisted like a Pi.',
		triggers: ['sexy move'],
		tags: ['dot', 'two-look', 'no-edges', 'long']
	},
	{
		id: 'oll-03',
		set: 'oll',
		name: 'Sune Dot',
		shortName: 'OLL 3',
		group: 'Dots',
		tier: 'advanced',
		algs: [
			{ moves: "f R U R' U' f' U' F R U R' U' F'" },
			{ moves: "F U R U' R' F' U F R U R' U' F'", label: 'no wide turns' },
			{ moves: "r' R2 U R' U r U2 r' U M'", label: 'slice' }
		],
		probability: '1/54',
		recognition:
			'A dot with exactly one corner already yellow — the front right as drawn. Both the left and the right faces carry two stickers.',
		notes:
			'The three twisted corners sit as they do in a Sune, so with the edges fixed you would be at OLL 27. Mirror of OLL 4.',
		triggers: ['sexy move'],
		mirrorOf: 'oll-04',
		tags: ['dot', 'mirror', 'long', 'no-edges']
	},
	{
		id: 'oll-04',
		set: 'oll',
		name: 'Anti-Sune Dot',
		shortName: 'OLL 4',
		group: 'Dots',
		tier: 'advanced',
		algs: [
			{ moves: "f R U R' U' f' U F R U R' U' F'" },
			{ moves: "F U R U' R' F' U' F R U R' U' F'", label: 'no wide turns' },
			{ moves: "M U' r U2 r' U' R U' R' M'", label: 'slice' }
		],
		probability: '1/54',
		recognition:
			'The mirror of OLL 3: a dot with a single finished corner, at the back right as drawn.',
		notes:
			'The corners match an Anti-Sune. The only thing separating this from OLL 3 is the middle turn of the algorithm — U here, U prime there — so read the corner twists carefully.',
		triggers: ['sexy move'],
		mirrorOf: 'oll-03',
		tags: ['dot', 'mirror', 'long', 'no-edges']
	},
	{
		id: 'oll-17',
		set: 'oll',
		name: 'Slash',
		shortName: 'OLL 17',
		group: 'Dots',
		tier: 'advanced',
		algs: [
			{ moves: "R U R' U R' F R F' U2 R' F R F'" },
			{ moves: "F R' F' R2 r' U R U' R' U' M'", label: 'slice' }
		],
		probability: '1/54',
		recognition:
			'A dot with two diagonally opposite corners already yellow, and nothing else on the top face.',
		notes:
			'The only dot with a diagonal pair of finished corners, so it is quick to spot even though the algorithm is a long one. Two sledgehammers, separated by a half turn.',
		triggers: ['sledgehammer'],
		tags: ['dot', 'diagonal', 'long', 'no-edges']
	},
	{
		id: 'oll-18',
		set: 'oll',
		name: 'Crown',
		shortName: 'OLL 18',
		group: 'Dots',
		tier: 'advanced',
		algs: [
			{ moves: "r U R' U R U2 r2 U' R U' R' U2 r" },
			{ moves: "R U2 R2 F R F' U2 M' U R U' r'", label: 'slice' },
			{ moves: "F R U R' U y' R' U2 R' F R F'", label: 'rotation' }
		],
		probability: '1/54',
		recognition:
			'A dot with the two back corners already yellow and a solid bar of three yellow stickers right across the front face.',
		notes:
			'The bar on the front is the giveaway — no other dot shows three in a row on a single side face. Compare with OLL 19, whose top face looks identical.',
		triggers: ['Aa insert'],
		tags: ['dot', 'long', 'no-edges', 'wide-turn']
	},
	{
		id: 'oll-19',
		set: 'oll',
		name: 'Bunny',
		shortName: 'OLL 19',
		group: 'Dots',
		tier: 'advanced',
		algs: [
			{ moves: "M U R U R' U' M' R' F R F'" },
			{ moves: "r' R U R U R' U' r R2 F R F'", label: 'wide-turn' },
			{ moves: "S' R U R' S U' R' F R F'", label: 'S-move' }
		],
		probability: '1/54',
		recognition:
			'A dot with the two back corners done, like OLL 18, but here the loose stickers split between the left and right faces instead of forming a bar on the front.',
		notes:
			'The slice opening makes this much shorter than the other two-corner dots — sexy move, put the slice back, sledgehammer. Check the side faces before you start, because the top face is the same as OLL 18.',
		triggers: ['sexy move', 'sledgehammer'],
		tags: ['dot', 'slice', 'short', 'no-edges']
	},
	{
		id: 'oll-20',
		set: 'oll',
		name: 'Checkers',
		shortName: 'OLL 20',
		group: 'Dots',
		tier: 'advanced',
		algs: [
			{ moves: "r U R' U' M2 U R U' R' U' M'" },
			{ moves: "M U R U R' U' M2 U R U' r'", label: 'other direction' },
			{ moves: "M' U2 M U2 M' U M U2 M' U2 M", label: 'pure slice' }
		],
		probability: '1/216',
		recognition:
			'The checkerboard: all four corners already yellow and all four edges flipped, so the top face alternates. Every side face shows a single sticker in its middle.',
		notes:
			'The rarest case on the cube — roughly one solve in two hundred and sixteen. It is all slice work, and the pure M version is worth learning for the pattern alone.',
		triggers: ['sexy move', 'Aa insert'],
		tags: ['dot', 'rare', 'slice', 'symmetric', 'no-edges']
	}
];

/**
 * The first look of two-look OLL: orient the last-layer edges, ignoring corners.
 * These are not OLL cases — they are the three edge shapes you can be left with.
 *
 * Only one algorithm is given for each, deliberately. The point of this step is to
 * have as little to remember as possible, and the three shapes are really one
 * algorithm written two ways plus both of them together.
 */
export const TWO_LOOK_OLL_EDGE_CASES: readonly AlgCase[] = [
	{
		id: 'eo-dot',
		set: 'oll-2look',
		name: 'Dot',
		shortName: 'Dot',
		group: 'Edge orientation',
		tier: 'intermediate',
		algs: [{ moves: "F R U R' U' F' f R U R' U' f'" }],
		probability: '1/8',
		recognition:
			'No yellow edges at all on the top face — just the centre. All four edges are flipped.',
		notes:
			'Run the line algorithm and then the L-shape algorithm and the dot is gone. Either order orients the edges; the order only changes which corner case you land in, and you have an algorithm for all seven of those.',
		triggers: ['sexy move'],
		tags: ['two-look', 'dot', 'edges']
	},
	{
		id: 'eo-line',
		set: 'oll-2look',
		name: 'Line',
		shortName: 'Line',
		group: 'Edge orientation',
		tier: 'intermediate',
		algs: [{ moves: "F R U R' U' F'" }],
		probability: '1/4',
		recognition:
			'A horizontal line of three yellow stickers across the middle of the top face: the left and right edges are already oriented.',
		notes:
			'Hold the line so it runs left to right, as drawn. Held front to back the same six moves leave you worse off, so check before you turn. This is also OLL 45, so nothing here is wasted.',
		triggers: ['sexy move'],
		tags: ['two-look', 'line', 'edges', 'short']
	},
	{
		id: 'eo-lshape',
		set: 'oll-2look',
		name: 'L Shape',
		shortName: 'L Shape',
		group: 'Edge orientation',
		tier: 'intermediate',
		algs: [{ moves: "f R U R' U' f'" }],
		probability: '1/2',
		recognition:
			'Two adjacent yellow edges with the centre, making a small L. As drawn the arms point to the right and towards you.',
		notes:
			'The most common of the three — it turns up half the time. It is the line algorithm with the two F turns made wide, so learn the line first and this arrives nearly free. This is also OLL 44.',
		triggers: ['sexy move'],
		tags: ['two-look', 'edges', 'wide-turn', 'common']
	}
];
